typo

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -100,8 +100,8 @@ jobs:
         run: |
           required_bins="contact_fcc cns haddock-restraints fast-rmsdmatrix"
           for bin in $required_bins; do
-            if [ ! -x "src/bin/$bin" ]; then
-              echo "src/bin/$bin is missing or not executable"; exit 1;
+            if [ ! -x "src/haddock/bin/$bin" ]; then
+              echo "src/haddock/bin/$bin is missing or not executable"; exit 1;
             fi
           done
           ls -l src/bin
